/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengembalian;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ALDHINYA
 */
public class TambahPengembalian extends javax.swing.JFrame {

    public TambahPengembalian() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        buttonTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idItemForm = new javax.swing.JTextField();
        alamatForm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaItemForm = new javax.swing.JTextField();
        peminjamanForm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaForm = new javax.swing.JTextField();
        ktpForm = new javax.swing.JTextField();
        pengembalianForm = new javax.swing.JTextField();
        jumlahForm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hpForm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totalForm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonKembali1 = new javax.swing.JButton();
        hargaSatuanLabel = new javax.swing.JLabel();
        tanggalKembali = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tambah Pengembalian");

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Item", "Nama Item", "Nama", "No. KTP", "No. HP", "Alamat", "Tgl Pinjam", "Tgl Kembali", "Jumlah", "Harga Satuan", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);
        if (tabelPeminjaman.getColumnModel().getColumnCount() > 0) {
            tabelPeminjaman.getColumnModel().getColumn(0).setHeaderValue("ID Item");
            tabelPeminjaman.getColumnModel().getColumn(3).setHeaderValue("No. KTP");
            tabelPeminjaman.getColumnModel().getColumn(4).setHeaderValue("No. HP");
            tabelPeminjaman.getColumnModel().getColumn(5).setHeaderValue("Alamat");
        }

        buttonTambah.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        buttonTambah.setText("Tambah Peminjaman");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Item :");

        idItemForm.setEditable(false);
        idItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idItemFormActionPerformed(evt);
            }
        });

        alamatForm.setEditable(false);
        alamatForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatFormActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat : ");

        namaItemForm.setEditable(false);
        namaItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaItemFormActionPerformed(evt);
            }
        });

        peminjamanForm.setEditable(false);
        peminjamanForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanFormActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Item :");

        jLabel5.setText("Tanggal Peminjaman :");

        namaForm.setEditable(false);
        namaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFormActionPerformed(evt);
            }
        });

        ktpForm.setEditable(false);
        ktpForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktpFormActionPerformed(evt);
            }
        });

        pengembalianForm.setEditable(false);
        pengembalianForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianFormActionPerformed(evt);
            }
        });

        jumlahForm.setEditable(false);
        jumlahForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahFormActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama :");

        jLabel7.setText("Tanggal Pengembalian :");

        jLabel8.setText("No. KTP");

        jLabel9.setText("Jumlah :");

        hpForm.setEditable(false);
        hpForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpFormActionPerformed(evt);
            }
        });

        jLabel10.setText("No. HP");

        totalForm.setEditable(false);
        totalForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFormActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Harga :");

        buttonKembali1.setText("Kembali");
        buttonKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembali1ActionPerformed(evt);
            }
        });

        hargaSatuanLabel.setVisible(false);

        tanggalKembali.setEditable(false);
        tanggalKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalKembaliActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Tanggal Hari Ini :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(213, 213, 213)
                .addComponent(hargaSatuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(idItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(alamatForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(namaItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(peminjamanForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(namaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(pengembalianForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jumlahForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(ktpForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(hpForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonKembali1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(hargaSatuanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ktpForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hpForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(buttonKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(namaItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(peminjamanForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(alamatForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pengembalianForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        if (idItemForm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih Data");
        } else {
            try {
                 String sql = "INSERT INTO pengembalian VALUES ('" + idItemForm.getText() + "','" + namaItemForm.getText() + "','" + namaForm.getText() + "','" + ktpForm.getText() + "','" + hpForm.getText() + "','" + alamatForm.getText() + "','" + peminjamanForm.getText() + "','" + pengembalianForm.getText() + "','" + jumlahForm.getText() + "','" + hargaSatuanLabel.getText() + "','" + totalForm.getText() + "','" + tanggalKembali.getText() +  "')";
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
                new Pengembalian().setVisible(true);
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        int baris = tabelPeminjaman.rowAtPoint(evt.getPoint());
        String idItem = tabelPeminjaman.getValueAt(baris, 0).toString();
        idItemForm.setText(idItem);
        String namaItem = tabelPeminjaman.getValueAt(baris, 1).toString();
        namaItemForm.setText(namaItem);
        String nama = tabelPeminjaman.getValueAt(baris, 2).toString();
        namaForm.setText(nama);
        String ktp = tabelPeminjaman.getValueAt(baris, 3).toString();
        ktpForm.setText(ktp);
        String hp = tabelPeminjaman.getValueAt(baris, 4).toString();
        hpForm.setText(hp);
        String alamat = tabelPeminjaman.getValueAt(baris, 5).toString();
        alamatForm.setText(alamat);
        String pinjam = tabelPeminjaman.getValueAt(baris, 6).toString();
        peminjamanForm.setText(pinjam);
        String kembali = tabelPeminjaman.getValueAt(baris, 7).toString();
        pengembalianForm.setText(kembali);
        String jumlah = tabelPeminjaman.getValueAt(baris, 8).toString();
        jumlahForm.setText(jumlah);
        String hargaSatuan = tabelPeminjaman.getValueAt(baris, 9).toString();
        hargaSatuanLabel.setText(hargaSatuan);
        String total = tabelPeminjaman.getValueAt(baris, 10).toString();
        totalForm.setText(total);
        tanggalKembali.setEditable(true);

    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void buttonKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembali1ActionPerformed
        new Pengembalian().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonKembali1ActionPerformed

    private void pengembalianFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengembalianFormActionPerformed

    private void ktpFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktpFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktpFormActionPerformed

    private void namaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFormActionPerformed

    private void peminjamanFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjamanFormActionPerformed

    private void namaItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaItemFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaItemFormActionPerformed

    private void alamatFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatFormActionPerformed

    private void idItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idItemFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idItemFormActionPerformed

    private void totalFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFormActionPerformed

    private void hpFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpFormActionPerformed

    private void tanggalKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalKembaliActionPerformed

    private void jumlahFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahFormActionPerformed

    private void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        model.addColumn("ID item");
        model.addColumn("Nama Item");
        model.addColumn("Nama");
        model.addColumn("No. KTP");
        model.addColumn("No. HP");
        model.addColumn("Alamat");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kembali");
        model.addColumn("Jumlah");
        model.addColumn("Harga Satuan");
        model.addColumn("Total Harga");
        try {
            String sql = "select * from peminjaman";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10), res.getString(11)});
            }
            tabelPeminjaman.setModel(model);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    private static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatForm;
    private javax.swing.JButton buttonKembali1;
    private javax.swing.JButton buttonTambah;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel hargaSatuanLabel;
    private javax.swing.JTextField hpForm;
    private javax.swing.JTextField idItemForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahForm;
    private javax.swing.JTextField ktpForm;
    private javax.swing.JTextField namaForm;
    private javax.swing.JTextField namaItemForm;
    private javax.swing.JTextField peminjamanForm;
    private javax.swing.JTextField pengembalianForm;
    private javax.swing.JTable tabelPeminjaman;
    private javax.swing.JTextField tanggalKembali;
    private javax.swing.JTextField totalForm;
    // End of variables declaration//GEN-END:variables
}
