/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peminjaman;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author ALDHINYA
 */
public class Peminjaman extends javax.swing.JFrame {

    public Peminjaman() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPeminjaman = new javax.swing.JTable();
        buttonHapus = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idItemForm = new javax.swing.JTextField();
        alamatForm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaItemForm = new javax.swing.JTextField();
        peminjamanForm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namaForm = new javax.swing.JTextField();
        ktpForm = new javax.swing.JTextField();
        pengembalianForm = new javax.swing.JTextField();
        jumlahForm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tombolEdit = new javax.swing.JButton();
        hpForm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totalForm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonKembali1 = new javax.swing.JButton();
        hargaSatuanLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Daftar Peminjaman");

        tabelPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Item", "Nama Item", "Nama", "No. KTP", "No. HP", "Alamat", "Tgl Pinjam", "Tgl Kembali", "Jumlah", "Harga Satuan", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPeminjaman);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonTambah.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        buttonTambah.setText("Tambah Peminjaman");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Item :");

        idItemForm.setEditable(false);
        idItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idItemFormActionPerformed(evt);
            }
        });

        alamatForm.setEditable(false);
        alamatForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatFormActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat : ");

        namaItemForm.setEditable(false);
        namaItemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaItemFormActionPerformed(evt);
            }
        });

        peminjamanForm.setEditable(false);
        peminjamanForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanFormActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Item :");

        jLabel5.setText("Tanggal Peminjaman :");

        namaForm.setEditable(false);
        namaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFormActionPerformed(evt);
            }
        });

        ktpForm.setEditable(false);
        ktpForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ktpFormActionPerformed(evt);
            }
        });

        pengembalianForm.setEditable(false);
        pengembalianForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianFormActionPerformed(evt);
            }
        });

        jumlahForm.setEditable(false);
        jumlahForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahFormActionPerformed(evt);
            }
        });
        jumlahForm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahFormKeyReleased(evt);
            }
        });

        jLabel6.setText("Nama :");

        jLabel7.setText("Tanggal Pengembalian :");

        jLabel8.setText("No. KTP");

        jLabel9.setText("Jumlah :");

        tombolEdit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tombolEdit.setText("EDIT");
        tombolEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditActionPerformed(evt);
            }
        });

        hpForm.setEditable(false);
        hpForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpFormActionPerformed(evt);
            }
        });

        jLabel10.setText("No. HP");

        totalForm.setEditable(false);
        totalForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFormActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Harga :");

        buttonKembali1.setText("Kembali");
        buttonKembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembali1ActionPerformed(evt);
            }
        });

        hargaSatuanLabel.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(218, 218, 218)
                .addComponent(hargaSatuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(idItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(alamatForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(namaItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(peminjamanForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(namaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(pengembalianForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jumlahForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(ktpForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(hpForm, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(buttonTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(hargaSatuanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ktpForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(hpForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(namaItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(peminjamanForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(alamatForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tombolEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonKembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(namaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jumlahForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(totalForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pengembalianForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        if (jumlahForm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih Data Dulu");
        } else {
            try {
                String sql = "delete from peminjaman where jumlah='" + jumlahForm.getText() + "'";
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        reset();
        loadTable();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        new TambahPeminjaman().setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void tabelPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPeminjamanMouseClicked
        int baris = tabelPeminjaman.rowAtPoint(evt.getPoint());
        String idItem = tabelPeminjaman.getValueAt(baris, 0).toString();
        idItemForm.setText(idItem);
        idItemForm.setEditable(true);
        String namaItem = tabelPeminjaman.getValueAt(baris, 1).toString();
        namaItemForm.setText(namaItem);
        namaItemForm.setEditable(true);
        String nama = tabelPeminjaman.getValueAt(baris, 2).toString();
        namaForm.setText(nama);
        namaForm.setEditable(true);
        String ktp = tabelPeminjaman.getValueAt(baris, 3).toString();
        ktpForm.setText(ktp);
        ktpForm.setEditable(true);
        String hp = tabelPeminjaman.getValueAt(baris, 4).toString();
        hpForm.setText(hp);
        hpForm.setEditable(true);
        String alamat = tabelPeminjaman.getValueAt(baris, 5).toString();
        alamatForm.setText(alamat);
        alamatForm.setEditable(true);
        String pinjam = tabelPeminjaman.getValueAt(baris, 6).toString();
        peminjamanForm.setText(pinjam);
        peminjamanForm.setEditable(true);
        String kembali = tabelPeminjaman.getValueAt(baris, 7).toString();
        pengembalianForm.setText(kembali);
        pengembalianForm.setEditable(true);
        String jumlah = tabelPeminjaman.getValueAt(baris, 8).toString();
        jumlahForm.setText(jumlah);
        jumlahForm.setEditable(true);
        String hargaSatuan = tabelPeminjaman.getValueAt(baris, 9).toString();
        hargaSatuanLabel.setText(hargaSatuan);
        String total = tabelPeminjaman.getValueAt(baris, 10).toString();
        totalForm.setText(total);

    }//GEN-LAST:event_tabelPeminjamanMouseClicked

    private void idItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idItemFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idItemFormActionPerformed

    private void alamatFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatFormActionPerformed

    private void namaItemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaItemFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaItemFormActionPerformed

    private void peminjamanFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peminjamanFormActionPerformed

    private void namaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFormActionPerformed

    private void ktpFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktpFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktpFormActionPerformed

    private void pengembalianFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pengembalianFormActionPerformed

    private void jumlahFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahFormActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        if (idItemForm.getText().isEmpty() || namaItemForm.getText().isEmpty() || namaForm.getText().isEmpty() || ktpForm.getText().isEmpty() || hpForm.getText().isEmpty() || alamatForm.getText().isEmpty() || peminjamanForm.getText().isEmpty() || pengembalianForm.getText().isEmpty() || jumlahForm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih Data Dulu");
        } else {
            editStok();
            try {
                String sql = "UPDATE peminjaman SET id_item = '" + idItemForm.getText() + "', nama_item = '" + namaItemForm.getText() + "', nama = '" + namaForm.getText() + "', ktp= '" + ktpForm.getText() + "', hp= '" + hpForm.getText() + "', alamat= '" + alamatForm.getText() + "', tgl_pinjam= '" + peminjamanForm.getText() + "', tgl_kembali= '" + pengembalianForm.getText() + "', jumlah= '" + jumlahForm.getText() + "', tot_harga= '" + totalForm.getText() + "' WHERE ktp='" + ktpForm.getText() + "'";
                java.sql.Connection conn = (Connection) koneksi.configDB();
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null, "Data Berhasil Diedit");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Perubahan Data Gagal" + e.getMessage());
            }
        }
        reset();
        loadTable();
    }//GEN-LAST:event_tombolEditActionPerformed

    private void hpFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hpFormActionPerformed

    private void totalFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFormActionPerformed

    private void buttonKembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembali1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_buttonKembali1ActionPerformed

    private void jumlahFormKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahFormKeyReleased
        try {
            if (jumlahForm.getText().isEmpty()) {

            } else {
                double totalHarga = Integer.parseInt(hargaSatuanLabel.getText()) * Integer.parseInt(jumlahForm.getText());
                totalForm.setText("" + totalHarga);
                return;
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jumlahFormKeyReleased

    private void editStok() {
        try {
            String dataStok = null;
            String stoknya = null;
            java.sql.Connection conn = (Connection) koneksi.configDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select * from item where nama='" + namaItemForm.getText() + "'");
            while (rs.next()) {
                dataStok = rs.getString("stok");
            }

            java.sql.Connection conn2 = (Connection) koneksi.configDB();
            Statement st2 = conn2.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from peminjaman where ktp='" + ktpForm.getText() + "'");
            while (rs2.next()) {
                stoknya = rs2.getString("jumlah");
            }

            int hitung = Integer.parseInt(dataStok) + Integer.parseInt(stoknya);
            int kurangiStok = hitung - Integer.parseInt(jumlahForm.getText());
            String sql2 = "UPDATE item SET stok = '" + kurangiStok + "' WHERE id='" + idItemForm.getText() + "'";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql2);
            pst.execute();
        } catch (Exception e) {
        }
    }

    private void reset() {
        idItemForm.setText("");
        namaItemForm.setText("");
        namaForm.setText("");
        ktpForm.setText("");
        hpForm.setText("");
        alamatForm.setText("");
        peminjamanForm.setText("");
        pengembalianForm.setText("");
        jumlahForm.setText("");
        totalForm.setText("");
        ktpForm.setText("");
    }

    private void loadTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        model.addColumn("ID item");
        model.addColumn("Nama Item");
        model.addColumn("Nama");
        model.addColumn("No. KTP");
        model.addColumn("No. HP");
        model.addColumn("Alamat");
        model.addColumn("Tgl Pinjam");
        model.addColumn("Tgl Kembali");
        model.addColumn("Jumlah");
        model.addColumn("Harga Satuan");
        model.addColumn("Total Harga");
        try {
            String sql = "select * from peminjaman";
            java.sql.Connection conn = (Connection) koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7), res.getString(8), res.getString(9), res.getString(10), res.getString(11)});
            }
            tabelPeminjaman.setModel(model);
        } catch (Exception e) {
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatForm;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali1;
    private javax.swing.JButton buttonTambah;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel hargaSatuanLabel;
    private javax.swing.JTextField hpForm;
    private javax.swing.JTextField idItemForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahForm;
    private javax.swing.JTextField ktpForm;
    private javax.swing.JTextField namaForm;
    private javax.swing.JTextField namaItemForm;
    private javax.swing.JTextField peminjamanForm;
    private javax.swing.JTextField pengembalianForm;
    private javax.swing.JTable tabelPeminjaman;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JTextField totalForm;
    // End of variables declaration//GEN-END:variables
}
